// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgHSKNztNwjPiyphcf3TNRJzZVC7XiQ8g',
    appId: '1:670307146743:web:857a40a8b2dc339ab82cf2',
    messagingSenderId: '670307146743',
    projectId: 'btkhackathon-f309b',
    authDomain: 'btkhackathon-f309b.firebaseapp.com',
    storageBucket: 'btkhackathon-f309b.firebasestorage.app',
    measurementId: 'G-DT8TV6JE01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9Jmwm4Gj2XWPVZrqHZ5dEinBtpzxbqXI',
    appId: '1:670307146743:android:483ffd6b5f67a151b82cf2',
    messagingSenderId: '670307146743',
    projectId: 'btkhackathon-f309b',
    storageBucket: 'btkhackathon-f309b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDQFQvEFmHg2n8xSzUE21xBA5Jhf2701I',
    appId: '1:670307146743:ios:045ebf39c75db557b82cf2',
    messagingSenderId: '670307146743',
    projectId: 'btkhackathon-f309b',
    storageBucket: 'btkhackathon-f309b.firebasestorage.app',
    iosClientId: '670307146743-qrooiglv68a0d8eqd781p83r10jd4lum.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeExpert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDQFQvEFmHg2n8xSzUE21xBA5Jhf2701I',
    appId: '1:670307146743:ios:045ebf39c75db557b82cf2',
    messagingSenderId: '670307146743',
    projectId: 'btkhackathon-f309b',
    storageBucket: 'btkhackathon-f309b.firebasestorage.app',
    iosClientId: '670307146743-qrooiglv68a0d8eqd781p83r10jd4lum.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeExpert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgHSKNztNwjPiyphcf3TNRJzZVC7XiQ8g',
    appId: '1:670307146743:web:88b0a4bbce6822d9b82cf2',
    messagingSenderId: '670307146743',
    projectId: 'btkhackathon-f309b',
    authDomain: 'btkhackathon-f309b.firebaseapp.com',
    storageBucket: 'btkhackathon-f309b.firebasestorage.app',
    measurementId: 'G-2XP9MX4R6H',
  );

}